#PCIE from UG810 - different part (real part not supported by webpack)
#                 Also, deleted lanes 4-7
set_property PACKAGE_PIN B5 [get_ports PCIE_RX0_N]
set_property PACKAGE_PIN B6 [get_ports PCIE_RX0_P]
set_property PACKAGE_PIN C3 [get_ports PCIE_RX1_N]
set_property PACKAGE_PIN C4 [get_ports PCIE_RX1_P]
set_property PACKAGE_PIN E3 [get_ports PCIE_RX2_N]
set_property PACKAGE_PIN E4 [get_ports PCIE_RX2_P]
set_property PACKAGE_PIN G3 [get_ports PCIE_RX3_N]
set_property PACKAGE_PIN G4 [get_ports PCIE_RX3_P]
set_property PACKAGE_PIN A3 [get_ports PCIE_TX0_N]
set_property PACKAGE_PIN A4 [get_ports PCIE_TX0_P]
set_property PACKAGE_PIN B1 [get_ports PCIE_TX1_N]
set_property PACKAGE_PIN B2 [get_ports PCIE_TX1_P]
set_property PACKAGE_PIN D1 [get_ports PCIE_TX2_N]
set_property PACKAGE_PIN D2 [get_ports PCIE_TX2_P]
set_property PACKAGE_PIN F1 [get_ports PCIE_TX3_N]
set_property PACKAGE_PIN F2 [get_ports PCIE_TX3_P]
set_property PACKAGE_PIN K5 [get_ports PCIE_CLK_QO_N]
set_property PACKAGE_PIN K6 [get_ports PCIE_CLK_QO_P]
set_property PACKAGE_PIN J14     [get_ports PCIE_PERST_LS]
set_property IOSTANDARD LVCMOS25 [get_ports PCIE_PERST_LS]
set_property PACKAGE_PIN J8      [get_ports PCIE_WAKE_B_LS]
set_property IOSTANDARD LVCMOS25 [get_ports PCIE_WAKE_B_LS]

set_property CONFIG_VOLTAGE 1.5 [current_design]
set_property CFGBVS GND         [current_design]

set_property PACKAGE_PIN P20 [get_ports rst_in]
set_property IOSTANDARD LVCMOS25 [get_ports rst_in]
