#PCIE from UG810 - different part (real part not supported by webpack)
#                 Also, deleted lanes 4-7
###set_property PACKAGE_PIN B5 [get_ports rx_n[0]]
###set_property PACKAGE_PIN B6 [get_ports rx_p[0]]
###set_property PACKAGE_PIN C3 [get_ports rx_n[1]]
###set_property PACKAGE_PIN C4 [get_ports rx_p[1]]
###set_property PACKAGE_PIN E3 [get_ports rx_n[2]]
###set_property PACKAGE_PIN E4 [get_ports rx_p[2]]
###set_property PACKAGE_PIN G3 [get_ports rx_n[3]]
###set_property PACKAGE_PIN G4 [get_ports rx_p[3]]
###set_property PACKAGE_PIN A3 [get_ports tx_n[0]]
###set_property PACKAGE_PIN A4 [get_ports tx_p[0]]
###set_property PACKAGE_PIN B1 [get_ports tx_n[1]]
###set_property PACKAGE_PIN B2 [get_ports tx_p[1]]
###set_property PACKAGE_PIN D1 [get_ports tx_n[2]]
###set_property PACKAGE_PIN D2 [get_ports tx_p[2]]
###set_property PACKAGE_PIN F1 [get_ports tx_n[3]]
###set_property PACKAGE_PIN F2 [get_ports tx_p[3]]
###set_property PACKAGE_PIN K5 [get_ports pclk_n]
###set_property PACKAGE_PIN K6 [get_ports pclk_p]
###set_property PACKAGE_PIN J14     [get_ports PCIE_PERST_LS]
###set_property IOSTANDARD LVCMOS25 [get_ports PCIE_PERST_LS]
###set_property PACKAGE_PIN J8      [get_ports PCIE_WAKE_B_LS]
###set_property IOSTANDARD LVCMOS25 [get_ports PCIE_WAKE_B_LS]

set_property LOC IBUFDS_GTE2_X0Y3 [get_cells clk_gen_0/pclk_ibuf]
set_property CONFIG_VOLTAGE 1.5 [current_design]
set_property CFGBVS GND         [current_design]

set_property PACKAGE_PIN P20 [get_ports prst_n]
set_property IOSTANDARD LVCMOS25 [get_ports prst_n]
