# 
# Implementation run script generated by Vivado
#  and modiified by Cliff
# 

puts "Implement (and time) Design"

if [file exists $plusDir.runs/impl_1/${myTop}_routed.dcp] {
    reset_run synth_1
}

launch_runs impl_1
wait_on_run impl_1


