# 
# Synthesis run script generated by Vivado
#  and modiified by Cliff
# 

puts "Synthesize Design"

if [file exists $plusDir.runs/synth_1/$myTop.dcp] {
    reset_run synth_1
}

launch_runs synth_1
wait_on_run synth_1

